pipeline {
    agent any
    stages {
        stage('Clone repository') {
            steps {
                git branch: 'main',
                credentialsId: 'git-jenkins',
                url: 'https://github.com/codentide/wt-application.git'
            }
        }
        stage('Build docker image') {
            steps {
                script {
                    withCredentials([
                        string(credentialsId: 'MONGO_URI', variable: 'MONGO_URI')
                    ]) {
                        sh "docker build --build-arg MONGO_URI=${MONGO_URI} -t microservice-proyecto:v1 ."
                    }
                }
            }
        }
        stage('Deploy docker container') {
            steps {
                script {
                    withCredentials([
                        string(credentialsId: 'MONGO_URI', variable: 'MONGO_URI')
                    ]) {
                        sh """
                            sed 's|\\${MONGO_URI}|${MONGO_URI}|g' docker-compose.yml > docker-compose-updated.yml
                            docker-compose -f docker-compose-updated.yml up -d
                        """
                    }
                }
            }
        }
    }
    post {
        always {
            emailext subject: "Build state: ${currentBuild.currentResult}",
                      body: "Build completed, more details at ${env.BUILD_URL}",
                      to: "marco.delboccio@est.iudigital.edu.co"
        }
    }
}
